# Generated by Django 2.1.1 on 2018-09-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('selecionada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respondida', models.BooleanField(default=False)),
                ('correta', models.BooleanField(default=False)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Ano')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Banca')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Disciplina')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Nivel')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Orgao')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='questoes.Pergunta'),
        ),
    ]
