# Generated by Django 2.1.1 on 2018-09-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('selecionada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='perfil.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Ano')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Banca')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Disciplina')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Nivel')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pergunta', to='questoes.Orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Respondida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondida', to='questoes.Alternativa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondida', to='perfil.Perfil')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondidas', to='questoes.Pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='respondida',
            field=models.ManyToManyField(related_name='pergunta', through='questoes.Respondida', to='perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='questoes.Pergunta'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='questoes.Pergunta'),
        ),
    ]
