# Generated by Django 2.1.1 on 2018-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
